version: "3.9"

services:
  #######
  # private environment which is not accessible from external network
  #######
  sut-in-private:
    build: ./sut
    ports:
      - "8080:8080"
    networks:
      private:

  # to proxy request by handling incoming webhook event
  # launch "wstunnel server" to welcome http request to SUT
  wstunnel-in-private:
    build: ./wstunnel/server
    depends_on:
      - sut-in-private
    ports:
      - "3330:3330"
    networks:
      private:


  #######
  # cloud environment which is out of private network
  #######
  # alternative https://webdriver.io/docs/selenium-standalone-service/
  # but to simplify Dockerfile for wdio
  selenium-server:
    ## ref: https://github.com/SeleniumHQ/docker-selenium#standalone
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210804
    ports:
      - "4444:4444"
    # https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container
    shm_size: "2g"
    networks: 
      cloud:

  # To testing in local (cloud)
  sut-in-cloud:
    build: ./sut
    ports:
      - "8001:8080"
    networks:
      cloud:

  # to establish websocket tunnel
  wstunnel-in-cloud:
    build: ./wstunnel/client
    depends_on:
      - wstunnel-in-private # another network
    ports:
      - "3331:3331"
    networks:
      cloud:

  wdio:
    build: ./wdio
    volumes:
      - ./wdio:/app:cached
    # without depends_on, it cannot resolve host name when using docker-compose run. 
    # [0-0] 2021-08-14T07:35:46.029Z ERROR webdriver: RequestError: getaddrinfo ENOTFOUND selenium-server
    depends_on: 
      - selenium-server
      - sut-in-cloud
      - wstunnel-in-cloud
    networks: 
      cloud:


networks:
  cloud:
  private: