version: "3.9"

services:
  tunnel-proxy:
    build: ./proxy
    networks: 
      - private
  sut:
    build: ./sut
    networks:
      - private
  
  # selenium hub / nodes
  selenium-server:
    ## ref: https://github.com/SeleniumHQ/docker-selenium#standalone
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210804
    ports:
      - "4444:4444"
    networks: 
      - cloud    

networks:
  cloud:
  private: